# Generated by Django 4.1 on 2022-10-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='files/')),
                ('type', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
