# Generated by Django 4.1 on 2023-01-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dna',
            name='seq_num',
            field=models.TextField(blank=True, default=''),
        ),
    ]
