# Generated by Django 4.1 on 2022-11-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphene', '0002_remove_graphene_size_graphene_size_x_graphene_size_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphene',
            name='hole',
            field=models.TextField(default=''),
        ),
    ]
