# Generated by Django 4.1 on 2022-11-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphene', '0003_graphene_hole'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphene',
            name='radius',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='graphene',
            name='cnt',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AlterField(
            model_name='graphene',
            name='hole',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='graphene',
            name='pbc',
            field=models.TextField(blank=True, default='None'),
        ),
    ]
